#!/bin/bash

#SBATCH --job-name=TDDFT_job_array     # job name, "OMP_run"
#SBATCH -t 7-00:00              # time limit: (D-HH:MM)
#SBATCH --mem=125000            # memory per node in MB
#SBATCH -a 1-240
#SBATCH -p sched_mit_ase
#SBATCH --cpus-per-task=40
#SBATCH --output=slurm.out     # file to collect standard output
#SBATCH --error=slurm.err      # file to collect standard errors

module load anaconda3/4.4.0
export LD_LIBRARY_PATH=''
module load gaussian/16.c01_avx2
# source ~/.bashrc
## eval "$(conda shell.bash hook)"
source activate xtb-env
echo $SMILES_PATH
echo $SLURM_ARRAY_TASK_ID
echo $SLURM_ARRAY_TASK_COUNT
echo $PATH
echo $XTB4STDAHOME
python TDDFT_from_SMILES.py --smiles_path $SMILES_PATH --index $SLURM_ARRAY_TASK_ID --nodes $SLURM_ARRAY_TASK_COUNT
