#!/bin/bash

#SBATCH --job-name=xtb_job_array     # job name, "OMP_run"
#SBATCH -t 7-0:00              # time limit: (D-HH:MM)
#SBATCH --mem=32000            # memory per node in MB
#SBATCH -a 1-240
#SBATCH --cpus-per-task=48
#SBATCH --output=slurm.out     # file to collect standard output
#SBATCH --error=slurm.err      # file to collect standard errors

module load anaconda/2022a
source ~/.bashrc
eval "$(conda shell.bash hook)"
conda activate xtb-env
echo $SMILES_PATH
echo $SLURM_ARRAY_TASK_ID
echo $SLURM_ARRAY_TASK_COUNT
echo $PATH
echo $XTB4STDAHOME
python xtb_job_array.py --smiles_path $SMILES_PATH --index $SLURM_ARRAY_TASK_ID --nodes $SLURM_ARRAY_TASK_COUNT